### ISSUE TITLE
老哥，写的不错，但是可以再封装一下

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [iDeMonnnnnn/DeMon-ARA#1]
就像强东哥在数据序列化框架里封装的intent函数一样，跳转到一个activity只需要
`openActivity<LeaderboardActivity>()`
然后可以在后面写个大括号，用lamda表达式的样子写回调，比较符合科特林的写法😄

**Comment by iDeMonnnnnn** [comment]
有的哦 core-ktx这个里面有进一步的kt封装，可见ActivityResultApi.kt

**Comment by SaltedFish-Extreme** [comment]
> 有的哦 core-ktx这个里面有进一步的kt封装，可见ActivityResultApi.kt

好的，我还没仔细看你的demo，只看了看你readme的用法😂
